package game.actors.creatures;

import edu.monash.fit2099.engine.actions.Action;
import edu.monash.fit2099.engine.actions.ActionList;
import edu.monash.fit2099.engine.actions.DoNothingAction;
import edu.monash.fit2099.engine.actors.Actor;
import edu.monash.fit2099.engine.actors.Behaviour;
import edu.monash.fit2099.engine.displays.Display;
import edu.monash.fit2099.engine.positions.GameMap;
import java.util.Map;
import java.util.TreeMap;

/**
 * An abstract base class for creatures within the game world. This class extends the base
 * {@link Actor} class and provides a common framework for managing creature behaviors using a
 * priority-based system. Subclasses are expected to define their specific characteristics and add
 * relevant behaviours.
 */
public abstract class Creature extends Actor {

    /**
     * A map storing the behaviours assigned to this creature, keyed by priority. Lower integer
     * values indicate higher priority. Uses TreeMap to potentially iterate in priority order if
     * keys represent priority directly, otherwise HashMap is fine. Changed to protected to allow
     * direct access in subclasses if absolutely needed, though using add/remove methods is
     * preferred.
     */
    protected Map<Integer, Behaviour> behaviours = new TreeMap<>();

    /**
     * Constructor for the Creature class. Initializes basic actor properties. Calls the constructor
     * of the superclass {@link Actor}.
     *
     * @param name        the name of the Creature
     * @param displayChar the character that will represent the Creature in the display
     * @param hitPoints   the Creature's starting hit points
     */
    public Creature(String name, char displayChar, int hitPoints) {
        super(name, displayChar, hitPoints);
    }

    /**
     * Selects and returns an action to perform on the current turn based on assigned behaviours. It
     * iterates through the creature's behaviours (potentially in priority order if using TreeMap)
     * and returns the {@link Action} generated by the first behaviour that provides one. If no
     * behaviour provides a valid action, it defaults to {@link DoNothingAction}.
     *
     * @param actions    collection of possible Actions for this Actor (typically not used directly
     *                   here, but provided by the engine)
     * @param lastAction The Action this Actor took last turn. Can do interesting things in
     *                   conjunction with Action.getNextAction()
     * @param map        the {@link GameMap} containing the Actor
     * @param display    the {@link Display} I/O object to which messages may be written
     * @return the Action to be performed, determined by the highest priority behaviour providing an
     * action, or DoNothingAction otherwise.
     */
    @Override
    public Action playTurn(ActionList actions, Action lastAction, GameMap map, Display display) {
        // TreeMap iterates keys in natural order (ascending), so lower numbers (higher priority) come first.
        for (Behaviour behaviour : behaviours.values()) {
            Action action = behaviour.getAction(this, map);
            if (action != null) {
                return action;
            }
        }
        // If no behaviour returned an action
        return new DoNothingAction();
    }

    /**
     * Adds a behaviour to the creature's behaviour map with a specified priority. If a behaviour
     * with the same priority already exists, it will be replaced. Lower numbers typically indicate
     * higher priority.
     *
     * @param priority  The integer priority of the behaviour (lower value means higher priority).
     * @param behaviour The {@link Behaviour} instance to add.
     */
    public void addBehaviour(int priority, Behaviour behaviour) {
        if (behaviour != null) {
            behaviours.put(priority, behaviour);
        }
    }

}